### ISSUE TITLE
AttributeError on authentication failure

### ISSUE THREAD

**Issue by cGV0ZQ** [atl/py-http-signature#1]
If you try a ssh agent authentication at it fails you get a misleading error: AttributeError: 'Signer' object has no attribute '_hash' instead of the SystemError no valid encryption which makes more sense. Adding self._hash = None below line 25  fixes the problem.

**Comment by atl** [comment]
Thanks for the feedback and the code suggestion. I've finally gotten back to the package and have implemented as you suggest.
